# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-19 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventstudyapi', '0002_userprofileextras'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileextras',
            old_name='file',
            new_name='file_key',
        ),
    ]
