# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-23 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventstudyapi', '0004_usersavednews_usersavedsearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersavednews',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='usersavednews',
            name='sentiment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
